In [ ]:
作業目標
活用矩陣運算，實做線性代數
作業重點
線性代數公式應用
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:
array1 = np.array([[10, 8], [3, 5]])

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?

In [2]:
import numpy as np

In [3]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [5]:
array1

array([[10,  8],
       [ 3,  5]])

In [7]:
b=np.linalg.inv(array1)
b

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [8]:
c=array1@b
c

array([[1., 0.],
       [0., 1.]])

In [ ]:
#2. 運用上列array計算特徵值、特徵向量?

In [12]:
w, v = np.linalg.eig(array1)

In [13]:
# eigenvalues
w

array([13.,  2.])

In [14]:
# eigenvectors
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [ ]:
#3. 運用上列array計算SVD?

In [17]:
u, s, vh = np.linalg.svd(array1)

In [18]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [19]:
s

array([13.94721714,  1.86417116])

In [20]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])